<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace App\GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a94010a0d736572766963652e70726f746f12077365727669636522160a074d657373616765120b0a036d736718012001280932340a044563686f122c0a0450696e6712102e736572766963652e4d6573736167651a102e736572766963652e4d65737361676522004224ca020f4170705c4563686f53657276696365e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

